### ISSUE TITLE
Exposing livenessProbe and readinessProbe Configuration in Task Manager and Job Manager Pod Spec

### ISSUE THREAD

**Issue by hjwalt** [spotify/flink-on-k8s-operator#105]
Right now the following is the default provided:

```
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 60
    successThreshold: 1
    tcpSocket:
      port: 6123
    timeoutSeconds: 10
```

Occasionally we encounter an unusual situation where the task manager did not reach RPC port start up, and was terminated by k8s. But when the port starts up while the pod is in terminating state, the job gets submitted, and killed eventually, creating a restart loop (which after some time resolves when magically the task manager starts before 25 seconds).

I can work on this and create pull request here if you think this is useful.
