### ISSUE TITLE
[Question] FlinkCluster stopping after first job execution

### ISSUE THREAD

**Issue by Donaschmi** [spotify/flink-on-k8s-operator#238]
# Context
We are currently working with the [TPC-DS benchmark](https://github.com/apache/flink/tree/master/flink-end-to-end-tests/flink-tpcds-test) which uses the [Table API](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/dev/table/tableapi/) to execute multiple SQL queries (around 100) each as a single job.

# Problem
When using the operator to deploy a Flink cluster along with the job with the following yaml example:
```yaml
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: tpcds
...
---
job:
    jarFile: /cache/flink-tpcds-1.14.3-jar-with-dependencies.jar
    className: org.apache.flink.table.tpcds.TpcdsTestProgramS3
...
```
this successfully creates a job executing the first query but Flink shuts down right after while the job submitter tries to create another job for the second query. When manually running the benchmark on a FlinkCluster, this issue does not appear.

Is this the expected behavior?

Best,
Donatien

**Comment by regadas** [comment]
Hi, @Donaschmi sorry for the late reply!

So `FlinkCluster` with a `Job` will represent a Job Cluster, meaning one job per cluster. Right now, if you want to run multiple jobs within the same cluster you will need to deploy  a `FlinkCluster` (no job spec) and then have a job that submits your jobs to this cluster;

Not sure about your requirements, but another thing you can do is to split jobs across multiple definitions, using args or different classNames i.e

```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: tpcds-1
...
---
job:
    jarFile: /cache/flink-tpcds-1.14.3-jar-with-dependencies.jar
    className: org.apache.flink.table.tpcds.TpcdsTestProgramS3Job1
...
```

```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: tpcds-2
...
---
job:
    jarFile: /cache/flink-tpcds-1.14.3-jar-with-dependencies.jar
    className: org.apache.flink.table.tpcds.TpcdsTestProgramS3Job2
...
```
