### ISSUE TITLE
Make JobManager / TaskManager not required

### ISSUE THREAD

**Issue by regadas** [spotify/flink-on-k8s-operator#243]
JobManager and TaskManager have a lot of sane defaults and for that reason we can make them not required.

A simple experimentation test cluster can be expressed as:

```yaml
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinksessioncluster-sample
  namespace: foobar
spec:
  flinkVersion: "1.14"
  image:
    name: flink:1.14.2
    pullPolicy: Always
```
