### ISSUE TITLE
[Question] Beam Python job not making progress

### ISSUE THREAD

**Issue by sumaithrim** [spotify/flink-on-k8s-operator#254]
We are trying to setup the Flink Session cluster infra to submit Beam Python jobs.

As per [python guide](https://github.com/spotify/flink-on-k8s-operator/blob/master/docs/python_guide.md), for the without server option - we have the session cluster setup (can see the flink UI with 8081 port forwarding). When we submit a simple Beam job, the job is submitted and the k8s job pod runs to completion, but the Flink UI itself is stuck making progress after the first chain! We are not seeing any error logs either on job-manager or task-manager (beam worker pool container) pods. We would love to get this setup working but are stuck at this (first) step of setting up the infra.

What we tried so far

- Reset session cluster to avoid any memory issue and then submit a simple job (literally read file and count number of lines in it)
- Try different i/o - gs object store, local file read
- Run vanilla wordcount example from apache_beam modules and that also gets stuck at first chain
- Leave the job running for longer than few mins (few hrs even) - no progress, show 0B - clearly some busy looping or io issues but not sure why/what's happening.
  - did a ping 8.8.8.8 from the python code to eliminate any n/w issues to outside internet
  - the job is clearly getting submitted to flink job manager (:8081) and so we are sure that there is no intra-pod communication issue either

![Task Manager logs](https://user-images.githubusercontent.com/96089608/153268626-3752ede5-0ebb-425c-ae17-c38ae12800fa.png)
![Job Manager logs](https://user-images.githubusercontent.com/96089608/153268998-ae68474b-5e55-44ad-940a-1204c78fbc4b.png)

Cluster config:
```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: beam-flink-cluster
spec:
  flinkVersion: "1.13"
  image:
    name: flink:1.13.5
    pullPolicy: Always
  jobManager:
    accessScope: Cluster
    securityContext:
      runAsUser: 9999
      runAsGroup: 9999
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
    ports:
      ui: 8081
  taskManager:
    replicas: 2
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
    sidecars:
      - name: beam-worker-pool
        image: apachebeam/python3.7_sdk:latest
        args: ["--worker_pool"]
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
```

a simple beam python pipeline

```
import argparse
import logging
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions


class CalculateLineLengthFn(beam.DoFn):
    def process(self, element):
        logging.info('element now ' + str(len(element)))
        return [len(element)]


parser = argparse.ArgumentParser()
parser.add_argument('--input',
                    help='input file path',
                    default='./data/data1.csv') # tried GS location as well
parser.add_argument('--output',
                    help='output file path',
                    default='./data/out')
known_args, pipeline_args = parser.parse_known_args()


with beam.Pipeline() as pipeline:
    pipeline = beam.Pipeline(options=PipelineOptions())
    csv_lines = (
        pipeline | 'Reading input file' >> beam.io.ReadFromText(
            known_args.input)
    )
    csv_lines | beam.Map(print)
    line_lengths = csv_lines | beam.ParDo(CalculateLineLengthFn())
    # line_lengths = csv_lines | beam.Map(len)

    line_lengths | 'Writing to output file' >> beam.io.WriteToText(
        known_args.output, file_name_suffix='.txt')

if __name__ == '__main__':
    logging.getLogger().setLevel(logging.DEBUG)
    pipeline.run()

```

Dockerfile for the new pipeline
```
FROM apache/beam_python3.7_sdk

WORKDIR /app
COPY . /app/

ENTRYPOINT ["python3", "--verison"]
```

k8s job config - that would get submitted to flink session cluster
```
apiVersion: batch/v1
kind: Job
metadata:
  name: beam-simple-line-count-py
spec:
  template:
    metadata:
      labels:
        app: beam-simple-line-count-py
    spec:
      containers:
        - name: beam-simple-line-count-py
          image: sumaithri/simple-line-count:latest
          command: ["python3"]
          args:
            - "-m"
            - "pipeline1"
            - "--runner=FlinkRunner"
            - "--flink_master=beam-flink-cluster-jobmanager:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
      restartPolicy: Never

```

Task Manager thread dump: https://paste-bin.xyz/37207

Attached some screenshots, cmds and configs used for reference. Has anyone similar issue? Any troubleshooting steps would be super helpful!
![Flink UI - stuck on early](https://user-images.githubusercontent.com/96089608/153268570-e636cf3f-cb37-427b-b167-14de9d9b90e7.png)
