### ISSUE TITLE
Job submitter doesn't work

### ISSUE THREAD

**Issue by htthao19** [spotify/flink-on-k8s-operator#280]
I deployed PyFlink cluster on K8s and met this issue.
The deployment yaml:

```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: wordcount
  namespace: flink-job
spec:
  flinkVersion: "1.14"
  image:
    name: pyflink:wordcount
    pullPolicy: Always
  jobManager:
    accessScope: Cluster
    ports:
      ui: 8081
    resources:
      limits:
        memory: "2048Mi"
        cpu: "500m"
  taskManager:
    replicas: 2
    resources:
      limits:
        memory: "2048Mi"
        cpu: "500m"
  job:
    pyFile: "word_count.py"
    parallelism: 2
    restartPolicy: Never
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
```

The submitter ran until reaching the MAX_RETRY, and show these logs:
```
Waiting...
tee: job_check_log: Permission denied
curl -sS "http://wordcount-jobmanager:8081/jobs"
tee: job_check_log: Permission denied
tee: job_check_log: Permission denied
tee: job_check_log: Permission denied
{"jobs":[]}
```

What did I do wrong?

**Comment by regadas** [comment]
Hi, @htthao19 not sure how are you building your py flink image; I just built one from https://github.com/spotify/flink-on-k8s-operator/tree/master/images and used the following definition with no issues:

```yaml
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: wordcount
spec:
  flinkVersion: "1.14"
  image:
    name: regadas/pyflink:1.14.2
    pullPolicy: Always
  job:
    pyFile: "examples/python/datastream/word_count.py"
    restartPolicy: Never
```
