### ISSUE TITLE
[Feature request]: Add ability to expose JobManager UI via Kind: Loadbalancer

### ISSUE THREAD

**Issue by Sudokamikaze** [spotify/flink-on-k8s-operator#319]
Hi,

Currently, exposing the JobManager is only possible via port-forwarding it by: `$ kubectl port-forward service/flink-illiatest-jobmanager -n flink-job 8081:8081` (EXAMPLE)
Because kind of service is hardcoded

I'd like to discuss an ability to expose any JobManager via LB, for example:
```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flink-illiatest
  namespace: flink-job
spec:
  flinkVersion: "1.14"
  image:
    name: flink:1.14.3-scala_2.12-java11
  jobManager:
    accessScope: Cluster
    ports:
      ui: 8081
      mode: LoadBalancer
```

Construction of code is an example, of course

To wrap it up, this FR is about:
* Un-hardcoding current kind of service, to expose job manager via LB(for those who need this), or to have a switch for NodeIP (default) and LB
* Add an ability to add annotations to service, for example exposing it via AWS ALB with internal mode enabled
* Documenting this feature

I can also start investigating on this topic, not very familiar with Go, but should not be a hard task from my point of view
Your suggestions/opinion is very welcome, thank you :)
