### ISSUE TITLE
JobSubmitter exit code is lost

### ISSUE THREAD

**Issue by live-wire** [spotify/flink-on-k8s-operator#424]
`Job.Mode: 'Blocking'`

- The jobsubmit script currently swallows the exit code of the main entrypoint [here](https://github.com/spotify/flink-on-k8s-operator/blob/master/controllers/flinkcluster/flinkcluster_submit_job_script.go#L156)

- Currently, the jobsubmitter is observed only while submitting the FlinkJob. The exit code for the submitter should also be observed and be potentially exposed in `FlinkCluster.Status.Components.Job` as `SubmitterExitCode`

```
status:
  components:
    job:
      completionTime: "2022-06-13T14:04:04Z"
      deployTime: "2022-06-13T11:19:14Z"
      id: somerandomId1234
      name: jobName1234
      startTime: "2022-06-13T11:32:02Z"
      state: Succeeded
      submitterName: flinkClusterName-job-submitter
      submitterExitCode: 0                                         <--- New field
``` 

`submitterExitCode` `-1` would mean that the submitter is still running. 
The downstream applications could potentially make use of this exitCode for retrying only a certain set of exit codes etc.
