### ISSUE TITLE
QUESTION: How to setup HA with Flink Operator

### ISSUE THREAD

**Issue by cheeyeo** [spotify/flink-on-k8s-operator#544]
Hi all,

I have been trying to setup a Flink session cluster running locally in a kind cluster with HA enabled. The setup includes 1 JM with 2 Taskmanagers using the following config:
```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: beam-flink-cluster
  namespace: default
spec:
  flinkVersion: "1.15.2"
  image:
    name: apache/flink:1.15.2
    pullPolicy: Always
  serviceAccountName: "flink-service-account"
  jobManager:
    replicas: 1
    accessScope: Cluster
    securityContext:
      runAsUser: 9999
      runAsGroup: 9999
    ports:
      ui: 8081
      rpc: 6123
      blob: 6124
      query: 6125
    # resources:
    #   limits:
    #     memory: "2048Mi"
    #     cpu: "500m"
  taskManager:
    replicas: 2
    securityContext:
      runAsUser: 9999
      runAsGroup: 9999
      fsGroup: 9999
    ports:
      data: 6121
      rpc: 6122
      query: 6125
    # resources:
    #   limits:
    #     memory: "2048Mi"
    #     cpu: "500m"
    volumes:
      - name: cache-volume
        emptyDir: {}
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      - name: artifacts-pv-storage
        persistentVolumeClaim:
          claimName: artifacts
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
      - mountPath: /tmp/beam-staging
        name: task-pv-storage
      - mountPath: /artifacts
        name: artifacts-pv-storage
    # Mount artifacts pv into beam worker pool as beam jobs run there ...
    sidecars:
      - name: beam-worker-pool
        image: apache/beam_python3.8_sdk:2.41.0
        args: ["--worker_pool"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: flink-aws-secret
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: flink-aws-secret
                key: secret_access_key
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: flink-aws-secret
                key: region
        volumeMounts:
          - mountPath: /artifacts
            name: artifacts-pv-storage
  envVars:
  - name: ENABLE_BUILT_IN_PLUGINS
    value: flink-s3-fs-hadoop-1.15.2.jar;flink-s3-fs-presto-1.15.2.jar;
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: flink-aws-secret
        key: access_key_id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: flink-aws-secret
        key: secret_access_key
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: flink-aws-secret
        key: region
  flinkProperties:
    taskmanager.memory.process.size: "2g"
    taskmanager.data.port: "6121"
    taskmanager.numberOfTaskSlots: "1"
    parallelism.default: "1"
    # queryable-state.enable: "true"
    state.backend: filesystem
    # Checkpoints invoked by job env
    state.checkpoints.dir: s3a://flinkexps/checkpoints/
    state.savepoints.dir: s3a://flinkexps/savepoints/
    classloader.resolve-order: parent-first
    # execution.checkpointing.interval: "10"
    execution.checkpointing.unaligned: "false"
    execution.checkpointing.max-concurrent-checkpoints: "2"   
    execution.checkpointing.interval: "60000"
    # Below for HA config
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3a://flinkexps/recovery/
    kubernetes.cluster-id: beam-flink-cluster
    high-availability.cluster-id: beam-flink-cluster
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: "10"
```

I was able to get the cluster setup and running but when I try to submit a batch job, it times out with the following error:
```
 {"errors":["org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application.\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:113)\n\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Could not execute application.\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)\n\t... 2 more\nCaused by: org.apache.flink.util.FlinkRuntimeException: Could not execute application.\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:88)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70)\n\tat org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:107)\n\t... 2 more\nCaused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Job BeamApp-flink-1207200740-373f8723_b9b40ddb-b844-4225-aeb9-e7713cc227f8 failed.\n\tat org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)\n\tat org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)\n\tat org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)\n\tat org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84)\n\t... 4 more\nCaused by: java.lang.RuntimeException: Job BeamApp-flink-1207200740-373f8723_b9b40ddb-b844-4225-aeb9-e7713cc227f8 failed.\n\tat org.apache.beam.runners.flink.FlinkPipelineRunner.main(FlinkPipelineRunner.java:198)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)\n\t... 7 more\nCaused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.flink.util.FlinkException: Could not upload job files.\n\tat org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:319)\n\tat org.apache.flink.api.java.ExecutionEnvironment.executeAsync(ExecutionEnvironment.java:1061)\n\tat org.apache.flink.client.program.ContextEnvironment.executeAsync(ContextEnvironment.java:132)\n\tat org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:70)\n\tat org.apache.beam.runners.flink.FlinkBatchPortablePipelineTranslator$BatchTranslationContext.execute(FlinkBatchPortablePipelineTranslator.java:195)\n\tat org.apache.beam.runners.flink.FlinkPipelineRunner.runPipelineWithTranslator(FlinkPipelineRunner.java:118)\n\tat org.apache.beam.runners.flink.FlinkPipelineRunner.run(FlinkPipelineRunner.java:85)\n\tat org.apache.beam.runners.flink.FlinkPipelineRunner.main(FlinkPipelineRunner.java:196)\n\t... 12 more\nCaused by: java.util.concurrent.ExecutionException: org.apache.flink.util.FlinkException: Could not upload job files.\n\tat java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)\n\tat org.apache.flink.api.java.ExecutionEnvironment.executeAsync(ExecutionEnvironment.java:1056)\n\t... 18 more\nCaused by: org.apache.flink.util.FlinkException: Could not upload job files.\n\tat org.apache.flink.runtime.client.ClientUtils.uploadJobGraphFiles(ClientUtils.java:86)\n\tat org.apache.flink.runtime.client.ClientUtils.extractAndUploadJobGraphFiles(ClientUtils.java:62)\n\tat org.apache.flink.client.deployment.application.executors.EmbeddedExecutor.lambda$submitJob$6(EmbeddedExecutor.java:176)\n\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)\n\tat org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$1(AkkaInvocationHandler.java:259)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)\n\tat org.apache.flink.util.concurrent.FutureUtils.doForward(FutureUtils.java:1389)\n\tat org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$null$1(ClassLoadingUtils.java:93)\n\tat org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68)\n\tat org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$guardCompletionWithContextClassLoader$2(ClassLoadingUtils.java:92)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)\n\tat org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$1.onComplete(AkkaFutureUtils.java:47)\n\tat akka.dispatch.OnComplete.internal(Future.scala:300)\n\tat akka.dispatch.OnComplete.internal(Future.scala:297)\n\tat akka.dispatch.japi$CallbackBridge.apply(Future.scala:224)\n\tat akka.dispatch.japi$CallbackBridge.apply(Future.scala:221)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\n\tat org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$DirectExecutionContext.execute(AkkaFutureUtils.java:65)\n\tat scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)\n\tat scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)\n\tat scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)\n\tat scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)\n\tat akka.pattern.PromiseActorRef.$bang(AskSupport.scala:621)\n\tat akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:24)\n\tat akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:23)\n\tat scala.concurrent.Future.$anonfun$andThen$1(Future.scala:532)\n\tat scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\n\tat scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\n\tat akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)\n\tat akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\n\tat scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\n\tat akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)\n\tat akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)\n\tat akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)\nCaused by: java.io.IOException: PUT operation failed: Read timed out\n\tat org.apache.flink.runtime.blob.BlobClient.putInputStream(BlobClient.java:357)\n\tat org.apache.flink.runtime.blob.BlobClient.uploadFile(BlobClient.java:406)\n\tat org.apache.flink.runtime.client.ClientUtils.uploadUserJars(ClientUtils.java:113)\n\tat org.apache.flink.runtime.client.ClientUtils.uploadAndSetUserJars(ClientUtils.java:105)\n\tat org.apache.flink.runtime.client.ClientUtils.uploadJobGraphFiles(ClientUtils.java:83)\n\t... 48 more\nCaused by: java.net.SocketTimeoutException: Read timed out\n\tat java.base/java.net.SocketInputStream.socketRead0(Native Method)\n\tat java.base/java.net.SocketInputStream.socketRead(Unknown Source)\n\tat java.base/java.net.SocketInputStream.read(Unknown Source)\n\tat java.base/java.net.SocketInputStream.read(Unknown Source)\n\tat java.base/java.net.SocketInputStream.read(Unknown Source)\n\tat org.apache.flink.runtime.blob.BlobOutputStream.receiveAndCheckPutResponse(BlobOutputStream.java:144)\n\tat org.apache.flink.runtime.blob.BlobOutputStream.finish(BlobOutputStream.java:107)\n\tat org.apache.flink.runtime.blob.BlobClient.putInputStream(BlobClient.java:354)\n\t... 52 more\n"]}
```
It seems that the Job cannot be submitted from the Job Manager to the task manager?

The logs from the Job Manager show the following errors:
```
2022-12-08 17:01:45,232 INFO  org.apache.flink.client.deployment.application.executors.EmbeddedExecutor [] - Submitting Job with JobId=88a92b658da6f5750ab002af7f82f0db.
2022-12-08 17:06:46,932 WARN  org.apache.flink.client.deployment.application.DetachedApplicationRunner [] - Could not execute application: 
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Job BeamApp-flink-1208170143-42ae0945_548f4b28-7a7a-478c-adc0-70015e0b5ff6 failed.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:107) ~[flink-dist-1.15.2.jar:1.15.2]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: Job BeamApp-flink-1208170143-42ae0945_548f4b28-7a7a-478c-adc0-70015e0b5ff6 failed.
	at org.apache.beam.runners.flink.FlinkPipelineRunner.main(FlinkPipelineRunner.java:198) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist-1.15.2.jar:1.15.2]
	... 7 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.flink.util.FlinkException: Could not upload job files.
```

I have tried to change the configuration multiple times by varying the task process memory size etc but to no avail.

I also read from the Flink documentation that in HA mode the job manager uses the pod ip address via the Kubernetes election service and the `jobmanager.rpc.address` config is ignored. If so, how do we obtain the provisioned job manager pod ip and pass it to the config?

What am I missing here that's not specified in the docs?

Thanks for any advice you can provide moving forward.
